### Slicer

In [1]:
import numpy as np
from PIL import Image
import glob
import matplotlib.pyplot as plt
import Func_file as Ff

In [2]:
path1 = 'data_train/64/'
path2 = 'data_train/64-sources/'

In [3]:
image_set = Ff.slicer(8, path1)

### Model

In [4]:
import keras 
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
#import matplotlib.animation as animation
from keras import backend as K
from keras.layers import Conv2D, MaxPooling2D, UpSampling2D, BatchNormalization, Input, Lambda, Flatten, Dense, Reshape, LeakyReLU, Concatenate, Dropout, Reshape
from keras.models import Model
import pickle
import tensorflow as tf

Using TensorFlow backend.


In [5]:
def SingleGrid(layer):
    
    X = Conv2D(32, (3,3), padding = 'same', activation = 'relu')(layer) 
    X = Conv2D(32, (3,3), padding = 'valid', activation = 'relu')(X)     
    X = MaxPooling2D((2,2))(X)                          
    X = BatchNormalization()(X)
    
    X = Conv2D(64, (5,5), padding = 'same', activation = 'relu')(X)      
    X = Conv2D(64, (5,5), padding = 'valid', activation = 'relu')(X)      
    X = MaxPooling2D((2,2))(X)
    X = BatchNormalization()(X)
    
    X = Conv2D(128, (7,7), padding = 'same', activation = 'relu')(X)
    X = Conv2D(128, (7,7), padding = 'valid', activation = 'relu')(X)      
    X = MaxPooling2D((2,2))(X)
    X = BatchNormalization()(X)
    
    X = Conv2D(256, (3,3), padding = 'same', activation = 'relu')(X)
    X = Conv2D(256, (3,3), padding = 'valid', activation = 'relu')(X)
    X = BatchNormalization()(X)
    
    X = Dense(256, activation = 'relu')(X)
    output1 = Reshape((256,))(X)
    
    return output1
    

In [6]:
def Comparator(layer):
    
    X = Dense(256)(layer)
    X = LeakyReLU()(X)
    
    X = Dense(32)(X)
    X = LeakyReLU()(X)
    
    X = Dense(5)(X)
    output2 = LeakyReLU()(X)
    
    return output2

In [7]:
def Fin_Model(input_shape):
    
    input3 = Input((128,64,3), name = 'Input')
    
    #=======================================================================#
    X1 = Lambda(lambda x:x[:,:64], name = 'Lambda_X1')(input3)
    
    X1 = Conv2D(32, (3,3), padding = 'same', activation = 'relu', name = '2D_X1_1')(X1) 
    X1 = Conv2D(32, (3,3), padding = 'valid', activation = 'relu', name = '2D_X1_2')(X1)     
    X1 = MaxPooling2D((2,2), name = 'Pool_X1_1')(X1)                          
    X1 = BatchNormalization(name = 'Norm_X1_1')(X1)
    
    X1 = Conv2D(64, (5,5), padding = 'same', activation = 'relu', name = '2D_X1_3')(X1)      
    X1 = Conv2D(64, (5,5), padding = 'valid', activation = 'relu', name = '2D_X1_4')(X1)      
    X1 = MaxPooling2D((2,2), name = 'Pool_X1_2')(X1)
    X1 = BatchNormalization(name = 'Norm_X1_2')(X1)
    
    X1 = Conv2D(128, (7,7), padding = 'same', activation = 'relu', name = '2D_X1_5')(X1)
    X1 = Conv2D(128, (7,7), padding = 'valid', activation = 'relu', name = '2D_X1_6')(X1)      
    X1 = MaxPooling2D((2,2), name = 'Pool_X1_3')(X1)
    X1 = BatchNormalization(name = 'Norm_X1_3')(X1)
    
    X1 = Conv2D(256, (3,3), padding = 'same', activation = 'relu', name = '2D_X1_7')(X1)
    X1 = Conv2D(256, (3,3), padding = 'valid', activation = 'relu', name = '2D_X1_8')(X1)
    X1 = BatchNormalization(name = 'Norm_X1_4')(X1)
    
    X1 = Dense(256, activation = 'relu', name = 'Dense_X1')(X1)
    X1 = Reshape((256,), name = 'Reshape_X1')(X1)
    #=======================================================================#
    
    #=======================================================================#
    X2 = Lambda(lambda x:x[:,64:], name = 'Lambda_X2')(input3)
    
    X2 = Conv2D(32, (3,3), padding = 'same', activation = 'relu', name = '2D_X2_1')(X2) 
    X2 = Conv2D(32, (3,3), padding = 'valid', activation = 'relu', name = '2D_X2_2')(X2)     
    X2 = MaxPooling2D((2,2), name = 'Pool_X2_1')(X2)                          
    X2 = BatchNormalization(name = 'Norm_X2_1')(X2)
    
    X2 = Conv2D(64, (5,5), padding = 'same', activation = 'relu', name = '2D_X2_3')(X2)      
    X2 = Conv2D(64, (5,5), padding = 'valid', activation = 'relu', name = '2D_X2_4')(X2)      
    X2 = MaxPooling2D((2,2), name = 'Pool_X2_2')(X2)
    X2 = BatchNormalization(name = 'Norm_X2_2')(X2)
    
    X2 = Conv2D(128, (7,7), padding = 'same', activation = 'relu', name = '2D_X2_5')(X2)
    X2 = Conv2D(128, (7,7), padding = 'valid', activation = 'relu', name = '2D_X2_6')(X2)      
    X2 = MaxPooling2D((2,2), name = 'Pool_X2_3')(X2)
    X2 = BatchNormalization(name = 'Norm_X2_3')(X2)
    
    X2 = Conv2D(256, (3,3), padding = 'same', activation = 'relu', name = '2D_X2_7')(X2)
    X2 = Conv2D(256, (3,3), padding = 'valid', activation = 'relu', name = '2D_X2_8')(X2)
    X2 = BatchNormalization(name = 'Norm_X2_4')(X2)
    
    X2 = Dense(256, activation = 'relu', name = 'Dense_X2')(X2)
    X2 = Reshape((256,), name = 'Reshape_X2')(X2)
    #=======================================================================#
    
    X = Concatenate(axis = 1, name = 'Concat_1')([X1, X2])
    
    X = Dense(256, name = 'Dense_X_1', activation = 'relu')(X)
    
    X = Dense(32, name = 'Dense_X_2', activation = 'relu')(X)
    
    X = Dense(5,activation = 'softmax', name = 'softmax')(X)
    
    X3 = Lambda(lambda x: x[:,:4]*1000)(X)
    X4 = Lambda(lambda x: x[:,4])(X)
    X4 = Reshape((1,))(X4)
    
    output3 = Concatenate(axis = 1, name = 'Concat_2')([X3, X4])
    print(output3.shape)
    #=======================================================================#
    
    model = Model(input3, output3)
    
    return model
    

### X_train

In [10]:
X_train = [ [ [ np.concatenate((img[i], img[j])) for j in range(len(img)) if i != j ] for i in range(len(img))] for img in image_set[:10]]

In [11]:
X_train = np.array(X_train)

In [12]:
X_train.shape

(10, 64, 63, 128, 64, 3)

In [13]:
del X_train

### Y_train

In [8]:
Y_train = np.load('y_trainiequalj.npy')

In [9]:
Y_train.shape

(588, 64, 64, 5)

### Fewer X_trains and Y_trains

In [10]:
fewer = Y_train[:,:,:,4] != 1
fewer[0][32]

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [11]:
X_train = np.array([ np.array([ np.array([ np.array(np.concatenate((image_set[img][i], image_set[img][j]))) for j in range(len(image_set[img])) if fewer[img][i][j] ]) for i in range(len(image_set[img]))]) for img in range(len(image_set[:10])) ])

In [12]:
image_set = np.array(image_set)

In [13]:
X_train = X_train.reshape(10*64)

In [18]:
x_train = X_train[0]
for i in range(1,640):
    x_train = np.concatenate((x_train, X_train[i]))
    print(X_train[i].shape[0])
#X_train = [ [ np.concatenate((x_train, X_train)) for j in range(X_train[i].shape[0]) ] for i in range(640) ]

4
3
4
4
4
3
3
3
3
4
3
4
4
3
4
3
4
4
4
4
3
3
3
4
4
4
4
4
3
2
4
2
3
4
4
4
4
3
2
4
3
4
3
4
3
4
3
4
2
4
3
3
4
4
3
3
3
4
4
3
4
4
4
4
3
3
3
2
3
3
4
3
4
4
3
4
4
3
4
4
4
3
4
2
4
4
4
4
4
3
3
2
4
4
3
3
4
4
3
3
3
4
4
2
3
3
4
3
4
3
4
4
4
3
4
4
4
4
4
4
3
3
4
3
4
4
4
4
3
4
4
4
2
3
2
3
3
3
4
4
4
4
3
3
4
4
4
4
3
4
4
4
4
3
3
4
3
4
4
2
4
4
3
3
4
4
4
4
4
4
3
3
4
3
3
3
4
3
4
3
2
4
4
4
4
3
3
3
4
3
4
4
4
4
3
2
4
3
3
4
3
3
3
3
3
3
4
4
4
4
4
4
4
3
4
3
4
3
3
4
4
4
3
4
3
3
4
2
4
2
3
4
4
4
3
4
4
4
3
4
4
4
4
2
4
3
3
4
3
4
3
4
4
3
4
4
4
4
4
4
3
4
3
4
4
2
3
4
4
3
4
4
4
3
3
4
4
4
4
4
3
4
3
4
3
3
3
2
4
4
3
3
4
4
4
3
4
3
4
3
2
3
4
4
4
3
4
4
2
3
4
4
3
3
4
4
3
3
3
4
4
4
3
4
3
3
4
4
4
3
3
4
3
3
3
4
3
3
4
4
3
2
4
4
4
3
4
4
3
2
3
3
4
3
4
4
4
3
3
4
3
2
4
4
4
3
4
4
3
4
4
3
4
4
4
2
4
4
4
3
4
4
3
4
3
3
4
4
4
3
4
4
4
4
4
2
4
3
2
4
3
3
4
3
3
4
3
4
3
3
3
3
3
3
4
4
3
4
4
4
4
2
4
4
4
3
4
4
3
4
3
4
4
4
4
3
4
2
3
3
4
4
3
4
3
4
4
3
2
3
4
2
4
2
4
3
2
3
3
3
4
3
4
4
4
4
4
4
3
3
4
4
3
4
4
4
4
4
4
3
4
4
3
3
4
3
4
4
4
3
3
3
4
4
3
3
4
4
3
4


In [ ]:
for i in range(1,58):
    X_train = np.array([ np.array([ np.array([ np.array(np.concatenate((image_set[img][i], image_set[img][j]))) for j in range(len(image_set[img])) if fewer[img][i][j] ]) for i in range(len(image_set[img]))]) for img in range(len(image_set[i*10:10+i*10])) ])
    X_train = X_train.reshape(10*64)
    for j in range(640):
        x_train = np.concatenate((x_train, X_train[j]))
    print(i,':',x_train.shape)
    if i%10 or i==57:
        np.save('X_train' + str(i) + '.npy', x_train)
    del X_train

1 : (4480, 128, 64, 3)
2 : (6720, 128, 64, 3)
3 : (8960, 128, 64, 3)
4 : (11200, 128, 64, 3)
5 : (13440, 128, 64, 3)
6 : (15680, 128, 64, 3)
7 : (17920, 128, 64, 3)
8 : (20160, 128, 64, 3)


In [230]:
x_train.shape

(2240, 128, 64, 3)

### Loss Func.

In [94]:
def loss_fun(y, y_hat):
    return K.mean(K.mean(K.square(y - y_hat)[:4] * 1000) + K.mean(K.square(y - y_hat)[-1]))

### Train

In [93]:
X_test = np.array([ [ [ np.concatenate((img[i], img[j])) for j in range(len(img)) if i != j ] for i in range(len(img))] for img in image_set[-8:]]).reshape(8*64*63,128,64,3)
y_test = Y_train[-8:].reshape(8*64*63,5)

In [110]:
akhari = Fin_Model((128,64,3))

(?, 5)


In [111]:
akhari.compile(optimizer = 'adam', loss = loss_fun, metrics = ['acc'])

In [112]:
for i in range(58):
    X_train = np.array([ [ [ np.concatenate((img[i], img[j])) for j in range(len(img)) if i != j ] for i in range(len(img))] for img in image_set[i*10 : 10 + i*10]])
    X_train = X_train.reshape(10*64*63,128,64,3)
    y_train = Y_train[i*10:i*10+10].reshape(10*64*63,5)
    akhari.fit(X_train, y_train, epochs = 5, batch_size = 32, validation_data = (X_test, y_test))
    del X_train

Train on 40320 samples, validate on 32256 samples
Epoch 1/5
40320/40320 [==============================] - 115s 3ms/step - loss: 11200671.0240 - acc: 0.8000 - val_loss: 9682442.1046 - val_acc: 0.9219
Epoch 2/5
40320/40320 [==============================] - 117s 3ms/step - loss: 10924402.5982 - acc: 0.9026 - val_loss: 9683121.0487 - val_acc: 0.9429
Epoch 3/5
40320/40320 [==============================] - 132s 3ms/step - loss: 11321149.5794 - acc: 0.8974 - val_loss: 9683307.3876 - val_acc: 0.9444
Epoch 4/5
40320/40320 [==============================] - 178s 4ms/step - loss: 10766836.4928 - acc: 0.9444 - val_loss: 9683298.1058 - val_acc: 0.9444
Epoch 5/5
40320/40320 [==============================] - 148s 4ms/step - loss: 11997631.0415 - acc: 0.9444 - val_loss: 9683328.2329 - val_acc: 0.9444
Train on 40320 samples, validate on 32256 samples
Epoch 1/5
40320/40320 [==============================] - 128s 3ms/step - loss: 10964137.9553 - acc: 0.9444 - val_loss: 9683341.4605 - val_acc: 0.9444


KeyboardInterrupt: 

In [82]:
pred = np.around(akhari.predict(X_test[-1*(64*63):]).reshape(64,63,5))

In [91]:
pred[5]

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0.

array([[61, 25, 34,  3, 41, 35, 10,  6],
       [54, 37, 16, 26, 15, 42,  2, 59],
       [18, 20, 39, 55, 33, 62, 44, 21],
       [23, 60,  0, 63, 43, 17, 46, 47],
       [14, 49, 58, 56,  5,  1, 52,  7],
       [31, 50, 57, 29, 12, 48, 32, 40],
       [53,  8, 27, 51, 24,  4, 13, 22],
       [19, 28,  9, 38, 45, 11, 36, 30]])